EQ_DEV_MODE = False
SERVER_NAME = 'test'
EQ_APPLICATION_VERSION = 'test_version'

EQ_SECRETS_FILE = 'secrets.yml'
EQ_ENABLE_CACHE = True
EQ_NEW_RELIC_ENABLED = False
EQ_RABBITMQ_ENABLED = False

EQ_SERVER_SIDE_STORAGE_DATABASE_DRIVER = "sqlite"
EQ_SERVER_SIDE_STORAGE_DATABASE_NAME = '//tmp/questionnaire.db'
EQ_SERVER_SIDE_STORAGE_DATABASE_HOST = None
EQ_SERVER_SIDE_STORAGE_DATABASE_PORT = 5432
EQ_SERVER_SIDE_STORAGE_USER_ID_ITERATIONS = 10000

EQ_SESSION_TIMEOUT_SECONDS = 45 * 60
EQ_SESSION_TIMEOUT_GRACE_PERIOD_SECONDS = 30
